name: yyfeed
version: 1

libraries:
- name: lxml
  version: 2.3.4
- name: PyCrypto
  version: 2.6
- name: MySQLdb
- name: sqlalchemy
  version: 0.9.7
- name: pylibmc

cron:
- description: jandan
  url: /fetcher
  schedule: "*/15 * * * *"
- description: ttrss
  url: /fetcher/ttrss
  schedule: "0 */3 * * *"
- description: ttrss_item
  url: /fetcher/ttrss/item
  schedule: "0 * * * *"
