name: yyfeed
version: 1

libraries:
- name: lxml
  version: 2.3.4
- name: PyCrypto
  version: 2.6
- name: MySQLdb
- name: sqlalchemy
  version: 0.9.7
- name: pylibmc

cron:
- description: jandan
  url: /fetcher
  schedule: "0 */2 * * *"
- description: ttrss
  url: /fetcher/ttrss
  schedule: "10 */3 * * *"
- description: ttrss_item
  url: /fetcher/ttrss/item
  schedule: "15,20,25 */3 * * *"
- description: iplaymtg
  url: /fetcher/iplaymtg
  schedule: "40 * * * *"
- description: iplaymtg_item
  url: /fetcher/iplaymtg/item
  schedule: "45,50,55 * * * *"
